# Generated by Django 6.0.3 on 2026-04-29 10:20

from django.db import migrations
from django.contrib.auth.models import User


def create_default_superuser(apps, schema_editor):
    """
    Create default superuser if it doesn't exist
    Username: Admin
    Password: Admin123
    """
    if not User.objects.filter(username='Admin').exists():
        User.objects.create_superuser(
            username='Admin',
            email='admin@doctorx.com',
            password='Admin123',
            first_name='Admin',
            last_name='User'
        )


def reverse_create_default_superuser(apps, schema_editor):
    """
    Reverse the migration - delete the default superuser
    """
    User.objects.filter(username='Admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_superuser, reverse_create_default_superuser),
    ]
