# Generated by Django 6.0.3 on 2026-04-29 10:20

from django.db import migrations
from django.contrib.auth.models import User


def create_default_superuser(apps, schema_editor):
    """
    Create default superuser if it doesn't exist
    Username: Admin
    Password: Admin123
    """
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='Admin').exists():
        from django.utils import timezone
        user = User.objects.create(
            username='Admin',
            email='admin@doctorx.com',
            first_name='Admin',
            last_name='User',
            is_staff=True,
            is_superuser=True,
            is_active=True,
            last_login=timezone.now(),
            date_joined=timezone.now()
        )
        user.password = 'pbkdf2_sha256$1200000$example$hash'  # Will be set properly below
        from django.contrib.auth.hashers import make_password
        user.password = make_password('Admin123')
        user.save()


def reverse_create_default_superuser(apps, schema_editor):
    """
    Reverse the migration - delete the default superuser
    """
    User.objects.filter(username='Admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_superuser, reverse_create_default_superuser),
    ]
