# Generated by Django 6.0.3 on 2026-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text="List of available days e.g. ['monday','wednesday']"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time_slots',
            field=models.CharField(blank=True, default='', help_text='Comma-separated time slots in 24-hour format e.g. 09:00,10:30,14:00', max_length=500),
        ),
    ]
