# Generated by Django 6.0.3 on 2026-04-30 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0025_performance_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='break_end_time',
            field=models.TimeField(blank=True, help_text='End time for break period', null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='break_start_time',
            field=models.TimeField(blank=True, help_text='Start time for break period', null=True),
        ),
        migrations.CreateModel(
            name='DoctorTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Time Slot',
                'verbose_name_plural': 'Doctor Time Slots',
                'ordering': ['date', 'start_datetime'],
                'unique_together': {('doctor', 'date', 'start_datetime')},
            },
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
    ]
