# Generated by Django 6.0.3 on 2026-04-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_remove_doctor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctortimeslot',
            index=models.Index(fields=['doctor', 'date', 'status'], name='doctors_doc_doctor__02ddbe_idx'),
        ),
        migrations.AddIndex(
            model_name='doctortimeslot',
            index=models.Index(fields=['doctor', 'date', 'start_datetime'], name='doctors_doc_doctor__685866_idx'),
        ),
    ]
