# Generated by Django 6.0.3 on 2026-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0027_doctortimeslot_doctors_doc_doctor__02ddbe_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='availability',
            name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='doctortimeslot',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='doctortimeslot',
            name='doctors_doc_doctor__02ddbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctortimeslot',
            name='doctors_doc_doctor__685866_idx',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='break_start_time',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='notes',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='slot_duration',
            field=models.IntegerField(default=30, help_text='Slot duration in minutes'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='DoctorTimeSlot',
        ),
    ]
