# Generated by Django 6.0.3 on 2026-04-30 07:12

from django.db import migrations, models


def convert_day_of_week_strings_to_integers(apps, schema_editor):
    """Convert string day_of_week values to integers"""
    DoctorSchedule = apps.get_model('doctors', 'DoctorSchedule')
    
    # Mapping from old string values to new integer values
    day_mapping = {
        'MON': 0,
        'TUE': 1,
        'WED': 2,
        'THU': 3,
        'FRI': 4,
        'SAT': 5,
        'SUN': 6,
    }
    
    # Update all existing records
    for schedule in DoctorSchedule.objects.all():
        if schedule.day_of_week in day_mapping:
            schedule.day_of_week = day_mapping[schedule.day_of_week]
            schedule.save()


def reverse_convert_day_of_week_integers_to_strings(apps, schema_editor):
    """Reverse: convert integer day_of_week values back to strings"""
    DoctorSchedule = apps.get_model('doctors', 'DoctorSchedule')
    
    # Mapping from integer values back to string values
    reverse_day_mapping = {
        0: 'MON',
        1: 'TUE',
        2: 'WED',
        3: 'THU',
        4: 'FRI',
        5: 'SAT',
        6: 'SUN',
    }
    
    # Update all existing records
    for schedule in DoctorSchedule.objects.all():
        if schedule.day_of_week in reverse_day_mapping:
            schedule.day_of_week = reverse_day_mapping[schedule.day_of_week]
            schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0028_alter_availability_unique_together_and_more'),
    ]

    operations = [
        # First convert the data
        migrations.RunPython(
            convert_day_of_week_strings_to_integers,
            reverse_convert_day_of_week_integers_to_strings
        ),
        # Then alter the field type
        migrations.AlterField(
            model_name='doctorschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
