# Generated by Django 6.0.3 on 2026-04-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0029_auto_20260430_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
