# Generated by Django 6.0.3 on 2026-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0031_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default='09:00', help_text="Doctor's shift start time"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default='17:00', help_text="Doctor's shift end time"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_duration',
            field=models.IntegerField(default=30, help_text="Slot duration in minutes"),
        ),
    ]
